version: "3"
services:
  app:
    build:
      context: .
      dockerfile: devDockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URL: postgresql://digitalmarketplace:digitalmarketplace@db:5432/digitalmarketplace

  db:
    image: postgres:10
    volumes:
      - dm-vol:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: digitalmarketplace
      POSTGRES_PASSWORD: digitalmarketplace
      POSTGRES_DB: digitalmarketplace

volumes:
  dm-vol:
