name: build-scan
on: 
  # Since branch protection prevents pushing to development, pushes only happen when merging PRs, so this runs only on merges (there's no way to set GitHub Actions to run on merges)
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: redhat-actions/buildah-build@v2
      with:
        image: dm-app-image
        containerfiles: |
          ./src/front-end/Dockerfile
  scan: 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: Azure/container-scan@v0
    #   with:
    #     image-name: dm-app-image
    - uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dm-app-image'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'